/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/boardC7.glb -o src/BoardC7.jsx 
*/

import React from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { createCopperMaterial } from "./materials/copperMaterial";
import { createElectricSweepMaterial } from "./materials/electricSweepMaterial";
import { createElectricSweepMaterial2 } from "./materials/electricSweepMaterial2";
import {
  createGlowBlueMaterial,
  createGlowBlueOuterMaterial,
} from "./materials/glowBlueMaterial";
import { createGoldMaterial } from "./materials/goldMaterial";
import { createHologramMaterial } from "./materials/hologramMaterial";
import { createIronBlackMaterial } from "./materials/ironBlackMaterial";
import { createIronMaterial } from "./materials/ironMaterial";
import { createBlackPlasticMaterial } from "./materials/blackPlasticMaterial";
import { FloatingSteam } from "./FloatingSteam"; // Import your new steam component

const BOARD_C7_URL = new URL("./assets/boardC7.glb", import.meta.url).href;

export const BoardC7 = React.forwardRef(function BoardC7(
  { topGroupOpen = false, topGroupRotation = 0, ...props },
  ref,
) {
  const { nodes, materials } = useGLTF(BOARD_C7_URL);
  const topGroupRef = React.useRef();
  const topRotationRef = React.useRef();
  const eliseRefs = React.useRef([]);
  const electricSweepShaderRef = React.useRef();
  const baseMaterial = materials["PBR.2"] ?? materials.PBR;
  const pbrMaterial = materials.PBR;
  const goldMaterial = React.useMemo(
    () => createGoldMaterial(baseMaterial),
    [baseMaterial],
  );
  const ironMaterial = React.useMemo(
    () => createIronMaterial(baseMaterial),
    [baseMaterial],
  );
  const ironBlackMaterial = React.useMemo(
    () => createIronBlackMaterial(baseMaterial),
    [baseMaterial],
  );
  const blackPlasticMaterial = React.useMemo(
    () => createBlackPlasticMaterial(baseMaterial),
    [baseMaterial],
  );
  const copperMaterial = React.useMemo(
    () => createCopperMaterial(baseMaterial),
    [baseMaterial],
  );
  const glowBlueMaterial = React.useMemo(() => createGlowBlueMaterial(), []);
  const glowBlueOuterMaterial = React.useMemo(
    () => createGlowBlueOuterMaterial(),
    [],
  );
  const hologramMaterial = React.useMemo(() => createHologramMaterial(), []);
  const electricSweepMaterial = React.useMemo(
    () => createElectricSweepMaterial(baseMaterial, electricSweepShaderRef),
    [baseMaterial],
  );
  const electricSweepMaterial2 = React.useMemo(
    () => createElectricSweepMaterial2(baseMaterial, electricSweepShaderRef),
    [baseMaterial],
  );
  const floatingSteam = React.useMemo(() => <FloatingSteam />, []);

  // Ready-to-use material variables:
  // baseMaterial, pbrMaterial, goldMaterial, ironMaterial, ironBlackMaterial,
  // copperMaterial, glowBlueMaterial, glowBlueOuterMaterial, hologramMaterial,
  // electricSweepMaterial.
  // Replace any mesh material with one of these according to your needs.

  useFrame((state, delta) => {
    glowBlueMaterial.uniforms.uTime.value = state.clock.elapsedTime;
    glowBlueOuterMaterial.uniforms.uTime.value = state.clock.elapsedTime;
    hologramMaterial.uniforms.uTime.value = state.clock.elapsedTime;
    if (electricSweepShaderRef.current) {
      electricSweepShaderRef.current.uniforms.uSweepTime.value =
        state.clock.elapsedTime;
    }

    eliseRefs.current.forEach((elise) => {
      if (elise) elise.rotation.y += delta * 0.82;
    });

    if (!topGroupRef.current || !topRotationRef.current) return;

    const targetY = topGroupOpen ? 1.718 : -1.518;
    const speed = Math.min(delta * 2, 1);
    const rotationSpeed = Math.min(delta * 4, 1);

    topGroupRef.current.position.y +=
      (targetY - topGroupRef.current.position.y) * speed;
    topRotationRef.current.rotation.y +=
      (topGroupRotation - topRotationRef.current.rotation.y) * rotationSpeed;
  });

  return (
    <group ref={ref} name="BoardC7" {...props} dispose={null}>
      <group
        ref={topGroupRef}
        name="BoardC7TopAssembly"
        position={[0.3, -1.518, 0.11]}
      >
        <group
          ref={topRotationRef}
          name="BoardC7TopAssemblyRotationPivot"
          position={[-0.3, 0, -0.11]}
        >
          <group
            name="BoardC7MenuAssembly"
            position={[0, 0.245, 0]}
            rotation={[0, 1.571, 0]}
          >
            <mesh
              geometry={nodes.topCPUlogo.geometry}
              material={materials["PBR.2"]}
              position={[0, 1.66, 0]}
            />
            <mesh
              geometry={nodes.cpuTopStands.geometry}
              material={ironMaterial}
              position={[0, 1.51, 0]}
            />
            <mesh
              geometry={nodes.behindTextMenu.geometry}
              material={electricSweepMaterial2}
              position={[212.253, -312.71, -384.497]}
            />
            <mesh
              geometry={nodes.homeTExt.geometry}
              material={glowBlueMaterial}
              position={[-2.255, -0.054, -0.401]}
            />
            <mesh
              geometry={nodes.homeTExt.geometry}
              material={glowBlueOuterMaterial}
              position={[-2.255, -0.054, -0.401]}
              scale={1.08}
              renderOrder={1}
            />
            <mesh
              geometry={nodes.behindHome.geometry}
              material={hologramMaterial}
              position={[-2.169, 0.052, -0.054]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.ebookText.geometry}
              material={glowBlueMaterial}
              position={[0.49, -0.054, -2.231]}
            />
            <mesh
              geometry={nodes.ebookText.geometry}
              material={glowBlueOuterMaterial}
              position={[0.49, -0.054, -2.231]}
              scale={1.08}
              renderOrder={1}
            />
            <mesh
              geometry={nodes.behindEbook.geometry}
              material={hologramMaterial}
              position={[0.064, 0.052, -2.145]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.newsText.geometry}
              material={glowBlueMaterial}
              position={[2.226, -0.054, 0.246]}
            />
            <mesh
              geometry={nodes.newsText.geometry}
              material={glowBlueOuterMaterial}
              position={[2.226, -0.054, 0.246]}
              scale={1.08}
              renderOrder={1}
            />
            <mesh
              geometry={nodes.behindNews.geometry}
              material={hologramMaterial}
              position={[2.14, 0.052, 0]}
            />
            <mesh
              geometry={nodes.onStcoksText.geometry}
              material={glowBlueMaterial}
              position={[-0.419, -0.062, 2.24]}
              rotation={[0, -1.571, 0]}
            />
            <mesh
              geometry={nodes.onStcoksText.geometry}
              material={glowBlueOuterMaterial}
              position={[-0.419, -0.062, 2.24]}
              rotation={[0, -1.571, 0]}
              scale={1.08}
              renderOrder={1}
            />
            <mesh
              geometry={nodes.behindStocks.geometry}
              material={hologramMaterial}
              position={[-0.029, 0.052, 2.119]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.standCpu.geometry}
              material={copperMaterial}
              position={[-0.003, 0.083, 0.002]}
              rotation={[0, -1.571, 0]}
            />
            <mesh
              geometry={nodes.cpuBasetop.geometry}
              material={ironMaterial}
              position={[0, -1.313, 0]}
            />
          </group>
        </group>
        <mesh
          geometry={nodes.cpuBase1.geometry}
          material={goldMaterial}
          position={[-0.3, -3.072, -0.11]}
        />
      </group>
      <group name="BoardC7BaseAssembly" position={[0, -0.023, 0]}>
        <mesh
          geometry={nodes.BorderPlane.geometry}
          material={ironMaterial}
          position={[0, 0.023, 0]}
        />
        <mesh
          geometry={nodes.BorderPlane1.geometry}
          material={ironMaterial}
          position={[0, -0.123, 0]}
        />
        <mesh
          geometry={nodes.soudureBaseCPU.geometry}
          material={ironMaterial}
          position={[0.001, 0.082, -0.003]}
        />
      </group>
      <group
        name="BoardC7ElectronicsAssembly"
        position={[49.57, -153.937, -191.042]}
      >
        <group
          name="BoardC7EliseAssembly"
          position={[-49.264, 154.258, 191.152]}
        >
          <mesh
            ref={(elise) => {
              eliseRefs.current[0] = elise;
            }}
            geometry={nodes.elise17.geometry}
            material={ironMaterial}
            position={[3.483, 0, 5.447]}
          />
          <mesh
            ref={(elise) => {
              eliseRefs.current[1] = elise;
            }}
            geometry={nodes.elise16.geometry}
            material={ironMaterial}
            position={[1.174, 0, 5.447]}
          />
          <mesh
            ref={(elise) => {
              eliseRefs.current[2] = elise;
            }}
            geometry={nodes.elise15.geometry}
            material={ironMaterial}
            position={[-1.092, 0, 5.447]}
          />
          <mesh
            ref={(elise) => {
              eliseRefs.current[3] = elise;
            }}
            geometry={nodes.elise14.geometry}
            material={ironMaterial}
            position={[1.106, 0, -5.447]}
          />
          <mesh
            ref={(elise) => {
              eliseRefs.current[4] = elise;
            }}
            geometry={nodes.elise13.geometry}
            material={ironMaterial}
            position={[-1.203, 0, -5.447]}
          />
          <mesh
            ref={(elise) => {
              eliseRefs.current[5] = elise;
            }}
            geometry={nodes.elise12.geometry}
            material={ironMaterial}
            position={[-3.468, 0, -5.447]}
          />
        </group>

        {/* 1. Your Original Circuit Mesh remains exactly where it was */}
        <mesh
          geometry={nodes.electroCircuit.geometry}
          material={electricSweepMaterial2}
          position={[-49.57, 153.945, 191.042]}
        />

        {/* 2. Place the Steam using matching coordinates, shifting Y up slightly */}
        <FloatingSteam
          count={30}
          spawnArea={[8, 2, 80]} // Reduced area size so it tightly hugs the CPU chip
          position={[-50.3, 154.01, 196.9]} // Matches the mesh X and Z exactly!
        />
        {/* 2. Place the Steam using matching coordinates, shifting Y up slightly */}
        <FloatingSteam
          count={30}
          spawnArea={[8, 2, 8]} // Reduced area size so it tightly hugs the CPU chip
          position={[-48.1, 154.01, 196.9]} // Matches the mesh X and Z exactly!
        />
        {/* <FloatingSteam
          count={30}
          spawnArea={[8, 2, 80]} // Reduced area size so it tightly hugs the CPU chip
          position={[-46.1, 154.01, 196.9]} // Matches the mesh X and Z exactly!
        /> */}
        <mesh
          geometry={nodes.soudureBase.geometry}
          material={ironMaterial}
          position={[60.389, -3.825, 0.672]}
        />
        <mesh
          geometry={nodes.puce.geometry}
          material={copperMaterial}
          position={[-154.039, 308.983, 385.068]}
        />
        <mesh
          geometry={nodes.coqueFan.geometry}
          material={blackPlasticMaterial}
          position={[-49.185, 154.168, 191.19]}
        />
        <mesh
          geometry={nodes["Plane-PBR"].geometry}
          material={materials.PBR}
          position={[-49.57, 153.937, 191.042]}
        />
      </group>
    </group>
  );
});

useGLTF.preload(BOARD_C7_URL);
